version: '3'
services:
  api:
    build: ./server/
    volumes:
      - /usr/src/app/node_modules
    ports:
      - '5000:5000'

  frontend:
    build: ./frontend/
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
