version: '3'
services:
  api:
    build: ./server/
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      - NODE_ENV=development

  web:
    build: ./frontend/
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development

  db:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
